name = "emailcontact"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

send_email = [
  { name = "EMAIL", destination_address = "imprezysweeto@gmail.com" }
]

[vars]
FROM = "formularz@imprezy-sweeto.pl"
TO = "imprezysweeto@gmail.com"
ALLOWED_ORIGIN = "https://imprezy-sweeto.pl"
